### ISSUE TITLE
fw to burn

### ISSUE THREAD

**Issue by yakaracolombia** [GrechTech/RetroRosetta#1]
hellos, retrorosetta is awesome, I compile openretropad but I need to ask, there are a universal fw for esp32 for all the listed controls or I need to upload only the fw corresponding to the controller I want to transmit, and another question is, the pinout is different, the documentation of rosetta show Wii/ext sda, scl to pins 15a/io25 and 13a/io26 in Retrorosetta v2 but this pins the control don't work but if I use the openretropad listed sda/io21 and scl/io22 the control work but disconnect after 1 minute of use, so, did you have a special fw for rosetta? you listed the pins for dreamcast, but in openretropad there no are esp32-dc-bt or br. thank you and sorry for my long request

**Comment by GrechTech** [comment]
Hi

I was working on a universal firmware for OpenRetroPad but I haven't been able to extensively test every mode for it, URL here, with compile option "esp32-universal-br": https://github.com/GrechTech/OpenRetroPad-GT/tree/multi-test  


Yep the pins for each console specifically are different between BlueRetro configuration and the OpenRetroPad configuration, the normal RetroRosetta pages just list the BlueRetro configs as originally these units were just for BR  


Regarding the issue on Wii i2c, does adding a 1K pull up resistor to SDA and SCL improve things?  



For Dreamcast, I'm afraid OpenRetroPad currently doesn't support it, the pin numbers are primarily for future reference there sorry (Using the proposed OpenRetroPad pin numbers), I'd considered working on Dreamcast support myself but other projects keep getting in the way before I was able to make any good progress  



Thanks

Thomas
GrechTech
